services:
  app:
    build: .
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")'"]
      interval: 5s
      timeout: 5s
      retries: 5
    condition: service_healthy

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    condition: service_healthy

volumes:
  mongodb_data:
  redis_data:
